export const demoData1 = [
  {
    1: "2",
    3: "293",
    35: "68.02",
    "Eldon Base for stackable storage shelf, platinum":
      '1.7 Cubic Foot Compact "Cube" Office Refrigerators',
    "Muhammed MacIntyre": "Barry French",
    "-213.25": "457.81",
    38.94: "208.16",
    Nunavut: "Nunavut",
    "Storage & Organization": "Appliances",
    0.8: "0.58",
  },
  {
    1: "3",
    3: "293",
    35: "2.99",
    "Eldon Base for stackable storage shelf, platinum":
      "Cardinal Slant-D� Ring Binder, Heavy Gauge Vinyl",
    "Muhammed MacIntyre": "Barry French",
    "-213.25": "46.71",
    38.94: "8.69",
    Nunavut: "Nunavut",
    "Storage & Organization": "Binders and Binder Accessories",
    0.8: "0.39",
  },
  {
    1: "4",
    3: "483",
    35: "3.99",
    "Eldon Base for stackable storage shelf, platinum": "R380",
    "Muhammed MacIntyre": "Clay Rozendal",
    "-213.25": "1198.97",
    38.94: "195.99",
    Nunavut: "Nunavut",
    "Storage & Organization": "Telephones and Communication",
    0.8: "0.58",
  },
  {
    1: "5",
    3: "515",
    35: "5.94",
    "Eldon Base for stackable storage shelf, platinum":
      "Holmes HEPA Air Purifier",
    "Muhammed MacIntyre": "Carlos Soltero",
    "-213.25": "30.94",
    38.94: "21.78",
    Nunavut: "Nunavut",
    "Storage & Organization": "Appliances",
    0.8: "0.5",
  },
  {
    1: "6",
    3: "515",
    35: "4.95",
    "Eldon Base for stackable storage shelf, platinum":
      "G.E. Longer-Life Indoor Recessed Floodlight Bulbs",
    "Muhammed MacIntyre": "Carlos Soltero",
    "-213.25": "4.43",
    38.94: "6.64",
    Nunavut: "Nunavut",
    "Storage & Organization": "Office Furnishings",
    0.8: "0.37",
  },
  {
    1: "7",
    3: "613",
    35: "7.72",
    "Eldon Base for stackable storage shelf, platinum":
      "Angle-D Binders with Locking Rings, Label Holders",
    "Muhammed MacIntyre": "Carl Jackson",
    "-213.25": "-54.04",
    38.94: "7.3",
    Nunavut: "Nunavut",
    "Storage & Organization": "Binders and Binder Accessories",
    0.8: "0.38",
  },
  {
    1: "8",
    3: "613",
    35: "6.22",
    "Eldon Base for stackable storage shelf, platinum":
      "SAFCO Mobile Desk Side File, Wire Frame",
    "Muhammed MacIntyre": "Carl Jackson",
    "-213.25": "127.7",
    38.94: "42.76",
    Nunavut: "Nunavut",
    "Storage & Organization": "Storage & Organization",
    0.8: "",
  },
  {
    1: "9",
    3: "643",
    35: "35",
    "Eldon Base for stackable storage shelf, platinum":
      "SAFCO Commercial Wire Shelving, Black",
    "Muhammed MacIntyre": "Monica Federle",
    "-213.25": "-695.26",
    38.94: "138.14",
    Nunavut: "Nunavut",
    "Storage & Organization": "Storage & Organization",
    0.8: "",
  },
  {
    1: "9",
    3: "643",
    35: "35",
    "Eldon Base for stackable storage shelf, platinum":
      "SAFCO Commercial Wire Shelving, Black",
    "Muhammed MacIntyre": "Monica Federle",
    "-213.25": "-695.26",
    38.94: "138.14",
    Nunavut: "Nunavut",
    "Storage & Organization": "Storage & Organization",
    0.8: "",
  },
  { 1: "" },
];

export const demoData2 = [
  {
    name: "Adeel Solangi",
    language: "Sindhi",
    id: "",
    bio: "Donec lobortis eleifend condimentum. Cras dictum dolor lacinia lectus vehicula rutrum. Maecenas quis nisi nunc. Nam tristique feugiat est vitae mollis. Maecenas quis nisi nunc.",
    version: "6.1",
  },
  {
    name: "Afzal Ghaffar",
    language: "Sindhi",
    id: "ENTOCR13RSCLZ6KU",
    bio: "Aliquam sollicitudin ante ligula, eget malesuada nibh efficitur et. Pellentesque massa sem, scelerisque sit amet odio id, cursus tempor urna. Etiam congue dignissim volutpat. Vestibulum pharetra libero et velit gravida euismod.",
    version: "1.88",
  },
  {
    name: "Aamir Solangi",
    language: "Sindhi",
    id: "IAKPO3R4761JDRVG",
    bio: "Vestibulum pharetra libero et velit gravida euismod. Quisque mauris ligula, efficitur porttitor sodales ac, lacinia non ex. Fusce eu ultrices elit, vel posuere neque.",
    version: "7.27",
  },
  {
    name: "Abla Dilmurat",
    language: "Uyghur",
    id: "5ZVOEPMJUI4MB4EN",
    bio: "Donec lobortis eleifend condimentum. Morbi ac tellus erat.",
    version: "2.53",
  },
  {
    name: "Adil Eli",
    language: "Uyghur",
    id: "6VTI8X6LL0MMPJCC",
    bio: "Vivamus id faucibus velit, id posuere leo. Morbi vitae nisi lacinia, laoreet lorem nec, egestas orci. Suspendisse potenti.",
    version: "6.49",
  },
  {
    name: "Adile Qadir",
    language: "Uyghur",
    id: "F2KEU5L7EHYSYFTT",
    bio: "Duis commodo orci ut dolor iaculis facilisis. Morbi ultricies consequat ligula posuere eleifend. Aenean finibus in tortor vel aliquet. Fusce eu ultrices elit, vel posuere neque.",
    version: "1.9",
  },
  {
    name: "Abdukerim Ibrahim",
    language: "Uyghur",
    id: "LO6DVTZLRK68528I",
    bio: "Vivamus id faucibus velit, id posuere leo. Nunc aliquet sodales nunc a pulvinar. Nunc aliquet sodales nunc a pulvinar. Ut viverra quis eros eu tincidunt.",
    version: "5.9",
  },
  {
    name: "Adil Abro",
    language: "Sindhi",
    id: "LJRIULRNJFCNZJAJ",
    bio: "Etiam malesuada blandit erat, nec ultricies leo maximus sed. Fusce congue aliquam elit ut luctus. Etiam malesuada blandit erat, nec ultricies leo maximus sed. Cras dictum dolor lacinia lectus vehicula rutrum. Integer vehicula, arcu sit amet egestas efficitur, orci justo interdum massa, eget ullamcorper risus ligula tristique libero.",
    version: "9.32",
  },
  {
    name: "Afonso Vilarchán",
    language: "Galician",
    id: "JMCL0CXNXHPL1GBC",
    bio: "Fusce eu ultrices elit, vel posuere neque. Morbi ac tellus erat. Nunc tincidunt laoreet laoreet.",
    version: "5.21",
  },
  {
    name: "Mark Schembri",
    language: "Maltese",
    id: "KU4T500C830697CW",
    bio: "Nam laoreet, nunc non suscipit interdum, justo turpis vestibulum massa, non vulputate ex urna at purus. Morbi ultricies consequat ligula posuere eleifend. Vivamus id faucibus velit, id posuere leo. Sed laoreet posuere sapien, ut feugiat nibh gravida at. Ut maximus, libero nec facilisis fringilla, ex sem sollicitudin leo, non congue tortor ligula in eros.",
    version: "3.17",
  },
  {
    name: "Antía Sixirei",
    language: "Galician",
    id: "XOF91ZR7MHV1TXRS",
    bio: "Pellentesque massa sem, scelerisque sit amet odio id, cursus tempor urna. Phasellus massa ligula, hendrerit eget efficitur eget, tincidunt in ligula. Morbi finibus dui sed est fringilla ornare. Duis pellentesque ultrices convallis. Morbi ultricies consequat ligula posuere eleifend.",
    version: "6.44",
  },
  {
    name: "Aygul Mutellip",
    language: "Uyghur",
    id: "FTSNV411G5MKLPDT",
    bio: "Duis commodo orci ut dolor iaculis facilisis. Nam semper gravida nunc, sit amet elementum ipsum. Donec pellentesque ultrices mi, non consectetur eros luctus non. Pellentesque massa sem, scelerisque sit amet odio id, cursus tempor urna.",
    version: "9.1",
  },
  {
    name: "Abdukerim Ibrahim",
    language: "Uyghur",
    id: "LO6DVTZLRK68528I",
    bio: "Vivamus id faucibus velit, id posuere leo. Nunc aliquet sodales nunc a pulvinar. Nunc aliquet sodales nunc a pulvinar. Ut viverra quis eros eu tincidunt.",
    version: 5.9,
  },
];

export const demoData3 = [
  {
    0: 1,
    "First Name": "Dulce",
    "Last Name": "Abril",
    Gender: "Female",
    Country: "United States",
    Age: 32,
    Date: "15/10/2017",
    Id: 1562,
  },
  {
    0: 2,
    "First Name": "Mara",
    "Last Name": "Hashimoto",
    Gender: "Female",
    Country: "Great Britain",
    Age: 25,
    Date: "16/08/2016",
    Id: 1582,
  },
  {
    0: 3,
    "First Name": "Philip",
    "Last Name": "Gent",
    Gender: "Male",
    Country: "France",
    Age: 36,
    Date: "21/05/2015",
    Id: 2587,
  },
  {
    0: 4,
    "First Name": "Kathleen",
    "Last Name": "Hanner",
    Gender: "Female",
    Country: "United States",
    Age: 25,
    Date: "15/10/2017",
    Id: 3549,
  },
  {
    0: 5,
    "First Name": "Nereida",
    "Last Name": "Magwood",
    Gender: "Female",
    Country: "United States",
    Age: 58,
    Date: "16/08/2016",
    Id: 2468,
  },
  {
    0: 6,
    "First Name": "Gaston",
    "Last Name": "Brumm",
    Gender: "Male",
    Country: "United States",
    Age: 24,
    Date: "21/05/2015",
    Id: 2554,
  },
  {
    0: 7,
    "First Name": "Etta",
    "Last Name": "Hurn",
    Gender: "Female",
    Country: "Great Britain",
    Age: 56,
    Date: "15/10/2017",
    Id: 3598,
  },
  {
    0: 8,
    "First Name": "Earlean",
    "Last Name": "Melgar",
    Gender: "Female",
    Country: "United States",
    Age: 27,
    Date: "16/08/2016",
    Id: 2456,
  },
  {
    0: 9,
    "First Name": "Vincenza",
    "Last Name": "Weiland",
    Gender: "Female",
    Country: "United States",
    Age: 40,
    Date: "21/05/2015",
    Id: 6548,
  },
];
